### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by Erfaniom** [JermaSites/sawpit#1]
I feel like the difficulty is too much and its too hard, I know that you have a lot of time but he is never gonna reach 25 there just isnt enough time to react after the command i feel like if you just add 1 second or 1.5 seconds it's gonna be enough

**Comment by sticks-stuff** [comment]
I've altered the timing slightly, see if that makes it any better. As a side note, you can see the maths for calculating how long you have to input on this line https://github.com/JermaSites/sawpit/blob/main/src.js#L487 

(Speed starts at 5 and increases by 0.1 for each successful input)

**Comment by Erfaniom** [comment]
it is sooooo much better thanks!
(and im really sorry for the late response i dont really use git much)

**Comment by s-crypt** [comment]
Is it still difficult to get to 25, but not impossible? It is not supposed to be easy

**Comment by Erfaniom** [comment]
yeah its absolutely possible but its not easy, when i first played it, it was impossible to get to 10
